version: 0.2

phases:
  pre_build:
    commands:
      - echo Install CI/CD Dependencies
      - pip3 install flake8 black pytest pytest-astropy pytest-cov
      - pip3 install pytest pytest-astropy pytest-cov
      - pip3 install git+https://github.com/dbarrous/hermes_core.git
      - apt-get install zip -y 
      - echo Lint with Black
      - black --check --diff lambda_function
      - echo Lint with Flake
      - flake8 --count --max-line-length 88 app.py lambda_function --exclude lambda_function_test_script.py
      - echo Perform Pytest Unit Testing
      - pytest --pyargs lambda_function --cov lambda_function
    
  build:
    commands:
      - echo Build started on `date`
      - echo Installing requirements...
      - pip3 install -r requirements.txt -t lambda_function
      - echo Zipping Lambda Function...
      - zip -r lambda_function.zip lambda_function
      - echo Pushing to S3...
      - aws s3 cp lambda_function.zip s3://swsoc-sorting-lambda

  post_build:
    commands:
      - echo Build completed on `date`
