version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing CI/CD Dependencies...
      - pip3 install flake8 black pytest pytest-astropy pytest-cov
      - pip3 install pytest pytest-astropy pytest-cov
      - pip3 install -r requirements.txt
      - echo ________________________________

      - echo Linting with Black...
      - black --check --diff lambda_function
      - echo ________________________________
      
      - echo Linting with Flake...
      - flake8 --count --max-line-length 88 lambda_function --exclude lambda_function_test_script.py
      - echo ________________________________
      

    
  build:
    commands:
      - echo Creating Zip Name...
      - |
        echo "Git Release Tag Script"
        
        TRIGGER=$CODEBUILD_WEBHOOK_TRIGGER
        NAME=dev_sorting_function_$(date +%s)
        
        if [[ $TRIGGER == *"tag/"* ]];then
          TAG=${TRIGGER:4}
          echo "Production Build, tagging with: $TAG"
          NAME=$(printenv TAG)_sorting_function_$(date +%s)
        fi
        
        export NAME
      - echo ________________________________
      
      - echo Installing requirements to Lambda Function...
      - pip3 install -r requirements.txt -t lambda_function
      - echo ________________________________
      
      - echo Zipping Lambda Function...
      - cd lambda_function
      - zip -r $NAME.zip .
      - echo ________________________________
      
      - echo Pushing to S3...
      - aws s3 cp $NAME.zip s3://swsoc-sorting-lambda/
      - echo ________________________________
      
      - echo Updating Deployment
      - aws codebuild start-build --project-name build_sdc_aws_pipeline_architecture --region us-east-2 --environment-variables-override name=LAMBDA_PIPELINE,value=SORTING,type=PLAINTEXT name=ZIP_NAME,value=$NAME.zip,type=PLAINTEXT
      - echo Build Successful - Lambda Successfully Zipped and Pushed to S3
  
