# This workflow will install Python dependencies, run tests, run linting, and test building docs
name: Testing

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    # Set up Python 10 to match the version of Python used in AWS Lambda
    - name: Set up Python 10
      uses: actions/setup-python@v3
      with:
        python-version: '10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt --upgrade

    - name: Run tests
      run: |
        pytest -s tests --cov=lambda_function/ --cov-report=html --log-cli-level=INFO 

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}